name: Update README

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  push:
    branches:
      - main  # Change to your default branch if not main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

   - name: Run Python script to update README
  run: |
    python update_readme.py

import requests

# Your code to fetch data and generate README content
readme_content = """
# Hi ğŸ‘‹, I'm Sanduni Lakshika
IT Undergraduate | University of Moratuwa

![Image](https://github.com/slakshika2026/slakshika2026/assets/110313255/4d66d5b4-7059-459e-856c-269f9e3fd5ba)
A coding enthusiast, music lover with a creative soul..!

- ğŸŒ± Iâ€™m currently learning MERN stack
- ğŸ‘¯ Iâ€™m looking to collaborate on web and mobile app development projects
- ğŸ˜„ Pronouns: Sandu
- âš¡ Fun fact: A Choco-Lover
- ğŸ“« How to reach me: **sandunilakshika2026@gmail.com**
- ğŸ“ Check out My blogs on: **https://medium.com/@sandunilakshika2026**

## Languages and Tools:
<!-- Add your languages and tools here -->

![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=slakshika2026&layout=compact)
![Streak](https://github-readme-streak-stats.herokuapp.com/?user=slakshika2026&)

## Connect with me:
<!-- Add your social links here -->
"""

with open("README.md", "w") as f:
    f.write(readme_content)


      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update README"
          git push
